export enum FontNames {
  GothamBlack = 'Gotham-Black',
  GothamBlackItalic = 'Gotham-BlackItalic',
  GothamBold = 'Gotham-Bold',
  GothamBoldItalic = 'Gotham-BoldItalic',
  GothamBook = 'Gotham-Book',
  GothamBookItalic = 'Gotham-BookItalic',
  GothamLight = 'Gotham-Light',
  GothamLightItalic = 'Gotham-LightItalic',
  GothamMedium = 'Gotham-Medium',
  GothamMediumItalic = 'Gotham-MediumItalic',
  GothamThin = 'Gotham-Thin',
  GothamThinItalic = 'Gotham-ThinItalic',
  GothamUltra = 'Gotham-Ultra',
  GothamUltraItalic = 'Gotham-UltraItalic',
  GothamXLight = 'Gotham-XLight',
  GothamXLightItalic = 'Gotham-XLightItalic',
}
